package org.aion;

import avm.Address;
import org.aion.avm.userlib.abi.ABIStreamingEncoder;

//TODO: it is expected that this file could be autogenerated by Aion toolchain in the future see https://github.com/aionnetwork/AVM/issues/401

public class AIP010Encoder {
  public static byte[] deploy(String tokenName, String tokenSymbol, String tokenUriBase) {
    return new ABIStreamingEncoder()
        .encodeOneString(tokenName)
        .encodeOneString(tokenSymbol)
        .encodeOneString(tokenUriBase)
        .toBytes();
  }
  
  public static byte[] aip010OwnerOf(byte[] tokenId) {
    return new ABIStreamingEncoder()
        .encodeOneString("aip010OwnerOf")
        .encodeOneByteArray(tokenId)
        .toBytes();
  }
  
  public static byte[] aip010ConsigneeOf(byte[] tokenId) {
    return new ABIStreamingEncoder()
        .encodeOneString("aip010ConsigneeOf")
        .encodeOneByteArray(tokenId)
        .toBytes();
  }
  
  public static byte[] aip010IsAuthorized(Address owner, Address authorizee) {
    return new ABIStreamingEncoder()
        .encodeOneString("aip010IsAuthorized")
        .encodeOneAddress(owner)
        .encodeOneAddress(authorizee)
        .toBytes();
  }
  
  public static byte[] aip010BalanceOf(Address owner) {
    return new ABIStreamingEncoder()
        .encodeOneString("aip010BalanceOf")
        .encodeOneAddress(owner)
        .toBytes();
  }
  
  //TODO: why wont this next line compile?
  /*
    public static byte[] aip010Transfer(Address currentOwner, Address newOwner, byte[] tokenId) {
      return new ABIStreamingEncoder()
          .encodeOneString("aip010Transfer")
          .encodeOneAddress(currentOwner)
          .encodeOneAddress(newOwner)
          .encodeOneByteArray(tokenId)
          .toBytes();
    );
    */
    
    public static byte[] aip010Consign(Address owner, Address consignee, byte[] tokenId) {
      return new ABIStreamingEncoder()
      .encodeOneString("aip010Consign")
      .encodeOneAddress(owner)
      .encodeOneAddress(consignee)
      .encodeOneByteArray(tokenId)
      .toBytes();
    }
    
    public static byte[] aip010Authorize(Address authorizee) {
      return new ABIStreamingEncoder()
      .encodeOneString("aip010Authorize")
      .encodeOneAddress(authorizee)
      .toBytes();
    }
    
    public static byte[] aip010Deauthorize(Address priorAuthorizee) {
      return new ABIStreamingEncoder()
      .encodeOneString("aip010Deauthorize")
      .encodeOneAddress(priorAuthorizee)
      .toBytes();
    }
    
    public static byte[] aip010Name() {
      return new ABIStreamingEncoder()
      .encodeOneString("aip010Name")
      .toBytes();
    }
    
    public static byte[] aip010Symbol() {
      return new ABIStreamingEncoder()
      .encodeOneString("aip010Symbol")
      .toBytes();
    }
    
    public static byte[] aip010TokenURI(byte[] tokenId) {
      return new ABIStreamingEncoder()
      .encodeOneString("aip010TokenURI")
      .encodeOneByteArray(tokenId)
      .toBytes();
    }
    
    public static byte[] aip010TotalSupply() {
      return new ABIStreamingEncoder()
      .encodeOneString("aip010TotalSupply")
      .toBytes();
    }
    
    public static byte[] aip010TokenByIndex(byte[] index) {
      return new ABIStreamingEncoder()
      .encodeOneString("aip010TokenByIndex")
      .encodeOneByteArray(index)
      .toBytes();
    }
    
    public static byte[] aip010TokenOfOwnerByIndex(Address owner, byte[] index) {
      return new ABIStreamingEncoder()
      .encodeOneString("aip010TokenOfOwnerByIndex")
      .encodeOneAddress(owner)
      .encodeOneByteArray(index)
      .toBytes();
    }
  }